name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Run widget tests for our flutter project.
      - run: flutter test

      # Build apk.
      - run: flutter build web

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@master
        with:
          name: web-build
          path: build/web

      # Download artifact for deployment.
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: web-build

      # List files
      - name: Display structure of build files
        run: ls -R
        working-directory: ./web

      # Deploy to Github pages
      - name: Deploy to GH Pages
        run: |
          cd build/web
          git init
          git config --global user.email markus.buergler@mohemian.com
          git config --global user.name markus-mohemian
          git status
          git remote add origin https://${{secrets.GITHUB_TOKEN}}@github.com/markus-mohemian/flutter-test.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Update pages"
          git push origin gh-pages -f
